version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Installing dependencies"
      - npm install

artifacts:
  files:
    - appspec.yml
    - scripts/**         # your lifecycle scripts (install.sh, start_server.sh, etc.)
    - **/*    
