version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Zipping app for deployment"
      - zip -r app.zip .

artifacts:
  files:
    - app.zip
